### ISSUE TITLE
yeah its totally your launcher when its the POR temp launcher that was found by a TLOPO staff

### ISSUE THREAD

**Issue by itsyaboyrocket** [Bob693/PythonLauncher#1]
https://piratesforums.co/threads/psa-investigation-into-the-retribution-client-and-protocol.13870/

**Comment by itsyaboyrocket** [comment]
![image](https://user-images.githubusercontent.com/33942724/40023622-51f91e28-5791-11e8-8070-c7e7635495a6.png)

**Comment by Bob693** [comment]
it was rewritten along time ago lol, considering you looked at that you can see the differences...
